# uipath-sample-proj-1 pipeline

trigger:
- main

variables:
- name: agent.preferPowerShellOnContainers
  value: 'True'

pool:
  vmImage: 'windows-latest'

container:
  image: uipathrobotas.azurecr.io/asuipathrobot:3
  endpoint: uipathrobotAS

steps:

- task: UiPathPack@2
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchTenantOne'
    outputPath: '$(Build.ArtifactStagingDirectory)'
    traceLevel: 'Information'
- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop