# uipath-sample-proj-1 pipeline

trigger:
- main

variables:
- name: agent.preferPowerShellOnContainers
  value: 'True'

pool:
  vmImage: 'windows-latest'

container:
  image: uipathrobotas.azurecr.io/asuipathrobot:3
  endpoint: uipathrobotAS

steps:

# - task: UiPathPack@2
#   inputs:
#     versionType: 'CurrentVersion'
#     projectJsonPath: '$(Build.SourcesDirectory)'
#     orchestratorConnection: 'UiPathOrchTenantOne'
#     outputPath: '$(Build.ArtifactStagingDirectory)'
#     traceLevel: 'Information'

- script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
  displayName: 'Build the artifact!'


- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop
- powershell: |
    Import-Module UiPath.Powershell
    $token = Get-UiPathAuthToken -AccountName $(tOneAccountName) -ClientId $(tOneClientId) -TenantName $(tOneTenantName) -UserKey $(tOneUserKey)
    Add-UiPathPackage -PackageFile $(Build.ArtifactStagingDirectory)\uipath-sample-proj-1.1.0.$(Build.BuildNumber).nupkg -AuthToken $token


# - task: UiPathDeploy@2
#   inputs:
#     orchestratorConnection: 'UiPathOrchTenantOne'
#     packagesPath: '$(Build.ArtifactStagingDirectory)'
#     folderName: 'DFolder'
#     entryPoints: 'Main.xaml'
#     traceLevel: 'Information'